# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-31 18:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentapp', '0004_auto_20181231_1545'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slider',
        ),
    ]
