# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-01 12:04
from __future__ import unicode_literals

import contentapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentapp', '0005_delete_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Имя слайда')),
                ('slide', models.ImageField(upload_to=contentapp.models.upload_slides)),
            ],
        ),
    ]
