# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-06 14:00
from __future__ import unicode_literals

import contentapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentapp', '0006_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Имя ссылки')),
                ('image', models.ImageField(upload_to=contentapp.models.upload_bannerlinks, verbose_name='Изображение')),
                ('link', models.CharField(blank=True, max_length=999, null=True, verbose_name='Вставьте ссылку')),
            ],
            options={
                'verbose_name_plural': 'Ссылки',
                'verbose_name': 'Ссылка',
            },
        ),
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'Баннер', 'verbose_name_plural': 'Баннеры'},
        ),
        migrations.AlterModelOptions(
            name='files',
            options={'verbose_name': 'Архив', 'verbose_name_plural': 'Архив'},
        ),
    ]
