# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-22 17:46
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_answer', models.CharField(choices=[('PA', 'Вариант ответа'), ('SA', 'Ответ вводимый через текстовое поле')], default='PA', max_length=50)),
                ('answer', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ответ')),
            ],
            options={
                'verbose_name_plural': 'Ответы',
                'verbose_name': 'Ответ',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия')),
                ('email', models.EmailField(blank=True, max_length=150, null=True, verbose_name='Электронная почта')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name_plural': 'Пользователи',
                'verbose_name': 'Пользователь',
            },
        ),
        migrations.CreateModel(
            name='PersonAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Answer', verbose_name='Ответ пользователя')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Person', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name_plural': 'Ответы пользователей',
                'verbose_name': 'Ответы пользователя',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('question', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Вопрос')),
            ],
            options={
                'verbose_name_plural': 'Вопросы',
                'verbose_name': 'Вопрос',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок')),
                ('is_activate', models.BooleanField(default=False, verbose_name='Активный?')),
            ],
            options={
                'verbose_name_plural': 'Тесты',
                'verbose_name': 'Тест',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Test', verbose_name='Тест'),
        ),
        migrations.AddField(
            model_name='question',
            name='trueAnswer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main.Answer', verbose_name='Верный ответ'),
        ),
        migrations.AddField(
            model_name='personanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Question', verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='test', chained_model_field='test', on_delete=django.db.models.deletion.CASCADE, to='main.Question', verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='answer',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Test', verbose_name='Тест'),
        ),
    ]
