# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-22 20:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='type_of_answer',
        ),
    ]
