# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-22 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_answer_type_of_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='type_of_answer',
            field=models.CharField(choices=[('PA', 'Вариант ответа'), ('SA', 'Ответ вводимый через текстовое поле')], default='PA', max_length=50),
        ),
    ]
