# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-24 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_answer_type_of_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personanswer',
            name='answer',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ответ пользователя'),
        ),
    ]
